# Site settings
title: Matthew Gouldie
description: Professional Bio & Simple Resume
# url: "https://www.matthewgouldie.com"

# User settings
username: Matthew Gouldie
user_description: I'm a Product Manager from Cape Town, South Africa, always searching for the next challenge; no task is too scary nor too difficult.
user_title: Product Manager
email: mb.gouldie@gmail.com
twitter_username: mbg_product
instagram_username: savlonious
facebook_username: matthew.gouldi
linkedin_username: matthew.gouldie
github_username:  mattonedge

exclude: ['package.json', 'src', 'node_modules', 'vendor']

