# Site settings
title: Matthew Gouldie
description: Professional Bio & Simple Resume
# url: "https://www.matthewgouldie.com"

# User settings
username: Matthew Gouldie
user_description: I'm a Product Manager from Cape Town, South Africa, always searching for the next challenge; always looking to learn and improve my understanding of the world.
user_title: Product Manager
email: mb.gouldie@gmail.com
twitter_username: mbg_markets
instagram_username: savlonious
facebook_username: matthew.gouldie
linkedin_username: matthew-gouldie-96464112a
github_username:  mattonedge

exclude: ['package.json', 'src', 'node_modules', 'vendor']

